//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int TrackingID { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<decimal> Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
